name: CI
on:
  push:
    branches:
      - main
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout badges branch
      run: git checkout origin/badges

    - name: Rebase badges on main
      run: git merge origin/main

    - name: Push badges branch
      run: git push -u origin/badges

    - name: Install
      run: npm ci
    - name: Coverage
      run: npm run coverage
    - name: Badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: badges